apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: taskmanager
  labels:
    app: taskmanager
data:
  PGRST_DB_SCHEMAS: "api"
  PGRST_DB_ANON_ROLE: "web_anon"
  PGRST_SERVER_PORT: "3000"
