apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: taskmanager
spec:
  type: LoadBalancer
  selector:
    app: taskmanager
    tier: frontend
  ports:
    - name: http-web
      port: 80
      targetPort: 80
      protocol: TCP
