apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: taskmanager
  labels:
    app: taskmanager
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: taskmanager
    tier: frontend
  ports:
    - name: http-web        # Istio protocol hint: treat as HTTP (enables L7 features)
      port: 80
      targetPort: 80
      protocol: TCP
