apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: taskmanager
  labels:
    app: taskmanager
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: UG9zdGdyZXNTZWN1cmUxMjMh
  POSTGRES_DB: dGFza2Ri
  PGRST_DB_URI: cG9zdGdyZXM6Ly9wb3N0Z3JlczpQb3N0Z3Jlc1NlY3VyZTEyMyFAcG9zdGdyZXMtc3ZjOjU0MzIvdGFza2Ri
