apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: taskmanager
  labels:
    app: taskmanager
type: Opaque
data:
  POSTGRES_USER: dGFza3VzZXI=
  POSTGRES_PASSWORD: dGFza3Bhc3M=
  POSTGRES_DB: dGFza21hbmFnZXI=
  PGRST_DB_URI: cG9zdGdyZXM6Ly90YXNrdXNlcjp0YXNrcGFzc0Bwb3N0Z3Jlcy1zdmM6NTQzMi90YXNrbWFuYWdlcg==
